version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - "> 5.4.2"
  - dependency-name: com.github.gmazzo:okhttp-mock
    versions:
    - 1.4.0
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
  - dependency-name: com.sun.xml.bind:jaxb-impl
    versions:
    - 3.0.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
