language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip

matrix:
  include:
    - jdk: openjdk9
      dist: xenial
    - jdk: openjdk10
      dist: xenial
    - jdk: openjdk11
      dist: xenial

after_success:
  - bash <(curl -s https://codecov.io/bash)
