name: publish
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - ".github/workflows/**"
  pull-request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - ".github/workflows/**"

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java
